apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web1
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: web1-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web1-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>¡Esta es la Web 1!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: web1-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web1
